sonar.projectKey=ciudadinteligente_back
sonar.projectName=ciudadinteligente_back
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.cpd.exclusions=**/entities/**

sonar.exclusions=\
  **/*.spec.ts,\
  **/*.test.ts,\
  **/node_modules/**,\
  **/dist/**,\
  **/main.ts,\
  **/coverage/**,\
  **/.scannerwork/**,\
  **/package-lock.json,\
  **/pnpm-lock.yaml,\
  **/.env,\
  **/.env.*,\
  **/sonar-project.properties,\
  **/src/app/utils/logos/**,\
  **/src/app/seeds/**,\
  **/src/app/common/interceptor/filesinspector.interceptor.ts

sonar.coverage.exclusions=\
  **/*.spec.ts,\
  **/*.test.ts,\
  **/tests/**,\
  **/seeds/**,\
  **/main.ts,\
  **/*.module.ts,\
  **/database/**,\
  **/dto/**,\
  **/entities/**,\
  **/middlewares/**,\
  **/jwt/**,\
  **/utils/response/**,\
  **/config/**,\
  **/models/**,\
  **/common/interceptor/**

sonar.sourceEncoding=UTF-8
