const UserLogActions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',

  GET_ALL_USERS: 'GET_ALL_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',

  GET_ALL_ROLES: 'GET_ALL_ROLES',

  GET_ALL_DEPENDENCIES: 'GET_ALL_DEPENDENCIES',
  GET_ALL_PROJECTS: 'GET_ALL_PROJECTS',
  UPDATE_DEPENDENCY: 'UPDATE_DEPENDENCY',
  GET_ALL_PROJECTS_FOR_DEPENDENCIES: 'GET_ALL_PROJECTS_FOR_DEPENDENCIES',
  CREATE_PROJECT_FOR_DEPENDENCY: 'CREATE_PROJECT_FOR_DEPENDENCY',
  DELETE_PROJECT_FOR_DEPENDENCY: 'DELETE_PROJECT_FOR_DEPENDENCY',
  CREATE_DEPENDENCY: 'CREATE_DEPENDENCY',
  GET_ALL_SYSTEMS_FOR_PROJECTS: 'GET_ALL_SYSTEMS_FOR_PROJECTS',
  UPDATE_PROJECT_BUDGET: 'UPDATE_PROJECT_BUDGET',
  UPDATE_PROJECT_DATES: 'UPDATE_PROJECT_DATES',
  UPDATE_SYSTEM_STATUS: 'UPDATE_SYSTEM_STATUS',
  CREATE_SYSTEM_FOR_PROJECT: 'CREATE_SYSTEM_FOR_PROJECT',
  GET_ALL_PROGRESS_FOR_SYSTEMS: 'GET_ALL_PROGRESS_FOR_SYSTEMS',
  ADD_PROGRESS_FOR_SYSTEM: 'ADD_PROGRESS_FOR_SYSTEM',
  EXPORT_REPORT_FOR_DEPENDENCY: 'EXPORT_REPORT_FOR_DEPENDENCY',
  UPDATE_PROGRESS_DESCRIPTION: 'UPDATE_PROGRESS_DESCRIPTION'
};

module.exports = { UserLogActions };
