sonar.projectKey=ciudadinteligente_portal
sonar.projectName=Ciudad_Inteligente-Portal
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.language=js

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/.scannerwork/**,\
  **/*.bak,\
  **/package-lock.json,\
  **/.env,\
  **/.env.*,\
  src/main.jsx,\
  src/main.css

sonar.coverage.exclusions=\
  src/main.jsx,\
  src/App.jsx,\
  src/api/**,\
  src/components/**,\
  src/views/**,\
  src/provider/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
